import random
import csv
from datasets import Dataset
import random 

leases_violations_scenarios = [
            "The tenant forgot to pay the rent.",
            "The tenant has unauthorized pets.",
            "The tenant made unauthorized structural changes.",
            "The tenant installed a satellite dish without permission.",
            "The tenant sublet the property without landlord approval.",
            "The tenant painted the apartment without consent.",
            "The tenant has been repeatedly late on rent payments.",
            "The tenant conducted business operations from a residential-only unit.",
            "The tenant replaced the locks without notifying the landlord.",
            "The tenant has caused noise disturbances reported by multiple neighbors.",
            "The tenant has parked vehicles in non-designated areas.",
            "The tenant has hung banners or signs that are not permitted.",
            "The tenant is keeping hazardous materials in the apartment.",
            "The tenant has excessive trash buildup, violating cleanliness policies.",
            "The tenant has made electrical modifications without approval.",
            "The tenant has a washer/dryer in the unit against the lease terms.",
            "The tenant has installed additional locks that violate fire safety codes.",
            "The tenant has failed to maintain smoke detector functionality.",
            "The tenant has unauthorized occupants living in the unit.",
            "The tenant has a barbecue grill on a balcony, against regulations.",
            "The tenant has left common areas consistently untidy.",
            "The tenant has installed a hot tub without permission.",
            "The tenant has pets that exceed the weight/number limit specified in the lease.",
            "The tenant uses storage areas for non-approved items.",
            "The tenant has blocked emergency exits with personal belongings.",
            "The tenant has failed to report damage that affects building safety.",
            "The tenant has altered the landscaping without permission.",
            "The tenant uses the premises for illegal activities.",
            "The tenant has tampered with existing building utilities.",
            "The tenant plays music at volumes that violate local noise ordinances.",
            "The tenant has failed to upkeep the garden as required by the lease.",
            "The tenant has constructed a shed in the backyard without permission.",
            "The tenant is hosting large parties that violate community rules.",
            "The tenant has posted advertising on the property's exterior.",
            "The tenant operates a daycare without the landlord's consent.",
            "The tenant has converted the living room into an additional bedroom.",
            "The tenant uses the apartment for Airbnb without approval.",
            "The tenant has not cleaned the pool, violating maintenance agreements.",
            "The tenant has a vehicle leaking oil on the driveway, against property rules.",
            "The tenant has set up a basketball hoop against community regulations.",
            "The tenant has drilled holes in exterior walls to mount a TV antenna.",
            "The tenant has bypassed electrical meters.",
            "The tenant has planted trees that interfere with underground utilities.",
            "The tenant has not adhered to the recycling and garbage disposal schedule.",
            "The tenant conducts loud workout sessions that disturb neighbors.",
            "The tenant has installed a security system that infringes on privacy rights.",
            "The tenant regularly smokes in non-smoking areas.",
            "The tenant has not maintained the rented appliances as per the lease agreement.",
            "The tenant has altered the function of safety devices in the apartment.",
            "The tenant has hung laundry on the balcony railing, against regulations.",
            "The tenant stores a motorbike in the hallway, blocking passage.",
            # "The tenant has a fish tank that exceeds the allowable gallon limit.",
            # "The tenant has affixed permanent light fixtures without approval.",
            # "The tenant uses the roof for personal storage, a safety violation.",
            # "The tenant has an aggressive breed of dog not permitted on the property.",
            # "The tenant leaves trash outside the door, attracting pests.",
            # "The tenant has covered more than the permitted percentage of the apartment floor with carpet.",
            # "The tenant feeds wildlife from the apartment, against policy.",
            # "The tenant has an unregistered car parked in the resident parking area.",
            # "The tenant misuses the laundry room for non-laundry activities.",
            # "The tenant has modified the front door with unauthorized decorations.",
            # "The tenant uses space heaters in violation of fire regulations.",
            # "The tenant has taken down a wall between rooms without permission.",
            # "The tenant runs a blog with loud equipment from the garage.",
            # "The tenant has replaced bathroom fixtures without the landlord’s consent.",
            # "The tenant uses fireworks on the property during holidays.",
            # "The tenant has painted the ceiling a dark color against the agreement.",
            # "The tenant has unauthorized solar panels installed on the roof.",
            # "The tenant practices drumming after hours, violating noise ordinances.",
            # "The tenant has modified plumbing to install an unauthorized dishwasher.",
            # "The tenant screens movies on the building exterior wall without consent.",
            # "The tenant has built a rock garden in the front yard, against landscaping rules.",
            # "The tenant has disconnected smoke alarms.",
            # "The tenant uses extension cords as a permanent wiring solution.",
            # "The tenant keeps a beehive on the balcony.",
            # "The tenant has placed large sculptures in the garden without approval.",
            # "The tenant has installed an unauthorized fence around the property.",
            # "The tenant uses an illegal type of barbeque grill on the patio.",
            # "The tenant has changed the exterior house color without consulting the landlord.",
            # "The tenant frequently locks the shared laundry room for private use.", 
            # "The tenant has installed an unauthorized window AC unit.",
            # "The tenant regularly hangs flags from the balcony, violating aesthetic rules.",
            # "The tenant has multiple vehicles parked in guest parking spaces.",
            # "The tenant operates heavy machinery in the garage, causing noise complaints.",
            # "The tenant has affixed non-standard window treatments.",
            # "The tenant has not removed holiday decorations in a timely manner.",
            # "The tenant uses the emergency exit for regular entry and exit.",
            # "The tenant has bypassed water usage limits during drought restrictions.",
            # "The tenant conducts unauthorized alterations to the bathroom layout.",
            # "The tenant has pets that are not listed on the lease agreement.",
            # "The tenant has installed loud exhaust fans in the kitchen.",
            # "The tenant has neglected necessary pest control, leading to infestations.",
            # "The tenant conducts chemical experiments in the basement.",
            # "The tenant has a trampoline in the backyard, against insurance policies.",
            # "The tenant uses the apartment's balcony for drone flying.",
            # "The tenant hosts commercial filming without permits or landlord permission.",
            # "The tenant has installed a non-compliant stair lift.",
            # "The tenant has built a makeshift greenhouse on the terrace.",
            # "The tenant has added unauthorized shower installations.",
            # "The tenant fails to maintain air conditioning units, causing leaks.",
            # "The tenant smokes cigars indoors against lease stipulations.",
            # "The tenant has erected a pirate radio antenna on the roof.",
            # "The tenant allows unauthorized guests to stay for extended periods.",
            # "The tenant has replaced carpet with tile without permission.",
            # "The tenant has built a pond in the backyard without proper containment.",
            # "The tenant has obstructed security cameras with decorations.",
            # "The tenant has unauthorized satellite radio equipment installed.",
            # "The tenant uses high-powered electronics that trip the building's main breaker.",
            # "The tenant has added a swing set in the front yard.",
            # "The tenant conducts unapproved yoga classes in the community room.",
            # "The tenant uses a kerosene heater in the winter.",
            # "The tenant has converted the garage into a recording studio.",
            # "The tenant has modified the balcony railings.",
            # "The tenant has illegal antennas installed on their vehicle.",
            # "The tenant uses excessive amounts of water for gardening.",
            # "The tenant has installed an unsanctioned retractable awning.",
            # "The tenant practices archery in the backyard.",
            # "The tenant has painted the interior doors in neon colors.",
            # "The tenant has unapproved political signs in the windows.",
            # "The tenant has built a skate ramp in the parking lot.",
            # "The tenant has installed a non-standard mailbox.",
            # "The tenant has a collection of exotic animals against lease terms.",
            # "The tenant uses glow-in-the-dark paint for outdoor decorations.",
            # "The tenant has modified the kitchen counters.",
            # "The tenant has a non-compliant compost bin in the garden.",
            # "The tenant allows water from their plants to leak onto lower balconies.",
            # "The tenant has unauthorized gym equipment in the living room.",
            # "The tenant uses the community room for private parties without booking.",
            # "The tenant has installed a personal security gate.",
            # "The tenant taps into the building’s electrical system for personal projects.",
            # "The tenant has left bikes and scooters blocking the emergency exit.",
            # "The tenant uses a fog machine for parties, triggering fire alarms.",
            # "The tenant has set up a large inflatable pool on the roof.",
            # "The tenant has installed a personal sauna in the bathroom without permission.",
            # "The tenant repaints the living room monthly, against lease terms.",
            # "The tenant has erected a large satellite dish on the front lawn.",
            # "The tenant has unauthorized advertising displayed on their vehicle.",
            # "The tenant uses their apartment for tarot and psychic readings commercially.",
            # "The tenant has converted the pantry into a small recording booth.",
            # "The tenant sells handmade crafts from the front porch.",
            # "The tenant has a large sculpture blocking communal pathways.",
            # "The tenant hosts a weekly podcast with live audiences, causing disturbances.",
            # "The tenant uses an unauthorized wood-burning stove.",
            # "The tenant has applied reflective film to all windows, affecting building aesthetics.",
            # "The tenant has bypassed the laundry room payment system.",
            # "The tenant has attached a hammock to the balcony railings.",
            # "The tenant has an oversized projector screen visible from the street.",
            # "The tenant has brought in a commercial-grade espresso machine, causing power issues.",
            # "The tenant has rigged a zip line from the balcony to the garden.",
            # "The tenant uses unauthorized, high-wattage outdoor lighting.",
            # "The tenant has multiple bird feeders attracting wildlife and pests.",
            # "The tenant has installed a personal jacuzzi in the basement.",
            # "The tenant has unauthorized neon signage in their windows.",
            # "The tenant has covered exterior brickwork with unauthorized murals.",
            # "The tenant breeds rabbits in the backyard.",
            # "The tenant has installed a batting cage in the side yard.",
            # "The tenant conducts auto repairs in the parking lot.",
            # "The tenant has unauthorized air purifying equipment visible outside.",
            # "The tenant keeps livestock in violation of urban agriculture restrictions.",
            # "The tenant has mounted large flags on the building facade.",
            # "The tenant uses the fire escape as a balcony garden.",
            # "The tenant has converted their closet into a microbrewery.",
            # "The tenant has hidden cameras outside their unit for security.",
            # "The tenant has installed a professional ballet barre and mirrors in the living room.",
            # "The tenant hosts VR gaming sessions that cause noise and crowd issues.",
            # "The tenant has modified the entryway to accommodate large pet enclosures.",
            # "The tenant has erected a wind turbine on their patio.",
            # "The tenant has installed stained glass windows.",
            # "The tenant has built a catwalk system across the ceiling for their cats.",
            # "The tenant uses a high-volume photo printer causing electrical circuit overloads.",
            # "The tenant has a loud vintage pinball machine in operation.",
            # "The tenant has set up a pottery kiln in their garage.",
            # "The tenant has unauthorized political rallies at their residence.",
            # "The tenant uses a drone for photography that invades neighbors' privacy.",
            # "The tenant has installed a permanent swing from a tree on the property.",
            # "The tenant practices saxophone at late hours, disturbing the peace.",
            # "The tenant has an outdoor fire pit that violates city fire codes.",
            # "The tenant uses the rooftop for sunset yoga classes without permission.",
            # "The tenant has placed oversized planters in communal hallways.",
            # "The tenant has unauthorized holographic displays during holidays.",
            # "The tenant has built an unauthorized gazebo in the common garden area.",
            # "The tenant has non-compliant solar fairy lights strung across the balcony.",
            # "The tenant allows their children to draw with chalk on the building’s exterior walls.",
            # "The tenant uses a gas-powered generator during power outages, against regulations.",
            # "The tenant has a loud air purifier running constantly, disturbing neighbors.",
            # "The tenant conducts online tutoring with loud group sessions.",
            # "The tenant has installed an unauthorized sliding door in the rear of the property.",
            # "The tenant uses part of the parking lot for weekend farmer's market stalls.",
            # "The tenant has a beekeeping setup on the roof without landlord approval.",
            # "The tenant plays bagpipes in the early morning hours.",
            # "The tenant has unauthorized waterbeds that pose a leakage risk.",
            # "The tenant runs a repair service for electronic devices from their apartment.",
            # "The tenant has installed a large fish pond in the front yard.",
            # "The tenant sets off fireworks from the driveway during non-holiday times.",
            # "The tenant uses the building's address for a high-volume mail-order business.",
            # "The tenant has a large collection of vintage cars that leak oil on the driveway.",
            # "The tenant operates a bread-making business using the apartment's kitchen.",
            # "The tenant has covered their apartment door with metallic foil.",
            # "The tenant has multiple wind chimes that create excessive noise.",
            # "The tenant uses the common area to hold weekly dance rehearsals.",
            # "The tenant has built a rock climbing wall on the side of the garage.",
            # "The tenant leaves sporting equipment in shared hallways, creating a fire hazard.",
            # "The tenant has installed a permanent metal detector at the entrance to their unit.",
            # "The tenant keeps exotic birds that are noisy during the day.",
            # "The tenant has converted the bathroom into a sauna room.",
            # "The tenant has unauthorized antennas and wires running across the roof.",
            # "The tenant has a large mural of their family painted on the garage door.",
            # "The tenant uses the patio for welding projects.",
            # "The tenant has a collection of large cacti that obstruct the walkway.",
            # "The tenant has installed a private basketball court in the back garden.",
            # "The tenant frequently uses smoke machines for party effects indoors.",
            # "The tenant has placed a shipping container in the yard for storage.",
            # "The tenant has converted the dining room into a small cinema.",
            # "The tenant hosts live streaming events that attract large crowds.",
            # "The tenant has unauthorized sculptures in the front yard.",
            # "The tenant has a permanent Christmas lights setup that they never take down.",
            # "The tenant has installed an electric vehicle charging station without permission.",
            # "The tenant keeps a horse in the large backyard, violating local zoning laws.",
            # "The tenant has set up an escape room game in their basement.",
            # "The tenant has multiple large satellite dishes for international broadcasts.",
            # "The tenant uses a loud industrial coffee grinder early in the morning.",
            # "The tenant has converted the attic into a live music studio.",
            # "The tenant has unauthorized thermal insulation on the exterior of the unit.",
            # "The tenant holds amateur car racing events in the property's parking lot.",
            # "The tenant has changed the color of the roof tiles without permission.",
            # "The tenant broadcasts radio shows from their living room.",
            # "The tenant has set up a boxing ring in their backyard.",
            # "The tenant uses the side of the building for large-scale projection mapping.",
            # "The tenant has installed an oversized bird feeder that attracts pests.",
            # "The tenant has unauthorized vending machines in the lobby.",
            # "The tenant has placed a large inflatable gorilla on the rooftop for advertising purposes.",
            # "The tenant runs a pet grooming business from their garage, causing traffic and noise.",
            # "The tenant has installed an elaborate treehouse that violates property height restrictions.",
            # "The tenant uses the backyard for motocross practice.",
            # "The tenant has unauthorized glow-in-the-dark paint on exterior pathways.",
            # "The tenant keeps a collection of antique, non-operational vehicles in the front yard.",
            # "The tenant has converted their living room into a virtual reality gaming arena.",
            # "The tenant has built a makeshift skate park in the common parking area.",
            # "The tenant uses loudspeakers for morning yoga sessions in the garden.",
            # "The tenant has a private server farm in their basement, overloading the electrical system.",
            # "The tenant has installed a pirate ship playground structure without consent.",
            # "The tenant uses the roof for commercial film shoots.",
            # "The tenant has multiple large aquariums that pose a risk of water damage.",
            # "The tenant conducts late-night carpentry workshops in their unit.",
            # "The tenant has transformed their balcony into a dense jungle with large plants.",
            # "The tenant operates a 24-hour live-streaming webcast, causing disturbances.",
            # "The tenant has an extensive laser light setup for night parties.",
            # "The tenant has unauthorized large banners hanging from the windows.",
            # "The tenant keeps livestock for urban farming against community regulations.",
            # "The tenant uses the laundry room to dye large batches of fabric.",
            # "The tenant has set up a permanent campfire spot in the backyard.",
            # "The tenant broadcasts a morning talk show from the balcony.",
            # "The tenant has a life-sized chess board in the front yard that blocks pedestrian paths.",
            # "The tenant has a DIY foam pit for stunt practice in the garden.",
            # "The tenant has installed multiple CCTV cameras beyond their unit, infringing on privacy.",
            # "The tenant uses the community gym for personal training services.",
            # "The tenant has changed the exterior window frames to an unauthorized color.",
            # "The tenant has built a high-powered telescope setup that encroaches on neighbor's spaces.",
            # "The tenant hangs laundry on the community fence line.",
            # "The tenant has a professional sand volleyball court installed in their backyard.",
            # "The tenant operates a ceramics kiln in their shed, violating fire safety regulations.",
            # "The tenant has multiple inflatable advertising figures in the garden.",
            # "The tenant uses a high-pressure washer at all hours, disturbing the peace.",
            # "The tenant has converted the guest bathroom into a darkroom for photography.",
            # "The tenant has excessive outdoor furniture that obstructs common areas.",
            # "The tenant keeps a vintage firetruck in the driveway as a personal project.",
            # "The tenant broadcasts amateur weather reports using loud equipment.",
            # "The tenant has a collection of large metal sculptures that are rusting and unsightly.",
            # "The tenant uses the building's façade for climbing practice.",
            # "The tenant has placed large stones and boulders in the front yard, altering the landscape.",
            # "The tenant hosts interactive theater performances in their backyard.",
            # "The tenant has a mobile home parked permanently in their driveway.",
            # "The tenant uses a professional-grade snow machine in winter for holiday decorations.",
            # "The tenant has installed a retractable movie screen that covers the entire side of the building.",
            # "The tenant has a rooftop lounge area that violates building codes.",
            # "The tenant has converted a walk-in closet into a recording studio for podcasts.",
            # "The tenant uses a foghorn as part of a morning wake-up ritual.",
            # "The tenant has installed non-standard shingles on the roof without approval.",
            # "The tenant keeps an old school bus in the yard for renovation into a home office.",
            # "The tenant has set up a seasonal haunted house attraction that exceeds noise levels.",
            # "The tenant has installed a commercial-grade pizza oven in the backyard without approval."
            # "The tenant uses the apartment's windows to display art installations that block light.",
            # "The tenant has constructed a permanent metal workshop in the garage.",
            # "The tenant hosts weekly outdoor cinema nights, disturbing the neighborhood.",
            # "The tenant has a makeshift bowling alley set up in the hallway.",
            # "The tenant uses the roof for beekeeping, against the lease agreement.",
            # "The tenant has placed multiple large advertisement billboards on the property.",
            # "The tenant has converted the basement into a public gaming lounge.",
            # "The tenant has a large inflatable slide in the backyard during summer.",
            # "The tenant holds cooking classes in the community kitchen without authorization.",
            # "The tenant has painted the front porch in bright, unauthorized colors.",
            # "The tenant has installed an unauthorized mechanical gate at the driveway.",
            # "The tenant uses a professional-grade trampoline that violates insurance policies.",
            # "The tenant has multiple birdhouses that attract an excessive number of birds.",
            # "The tenant has unauthorized exterior lighting that affects neighboring properties.",
            # "The tenant uses the communal terrace for private sculpture classes.",
            # "The tenant keeps a refrigerated trailer parked in their assigned parking space.",
            # "The tenant has erected a large banner on the building’s side for personal messages.",
            # "The tenant has placed oversized planters that block the main walkways.",
            # "The tenant uses a loud intercom system for personal announcements.",
            # "The tenant has turned the sunroom into a spa treatment area.",
            # "The tenant hangs historical flags that cover part of the building's facade.",
            # "The tenant has installed unauthorized stained glass panels in the common hall windows.",
            # "The tenant holds silent disco nights in the parking lot, causing crowding.",
            # "The tenant has a permanent display of vintage motorcycles in the garden.",
            # "The tenant has built an ice skating rink in the backyard during winter.",
            # "The tenant uses a loud, commercial-grade carpet cleaner late at night.",
            # "The tenant has a high-frequency ham radio setup that interferes with local communications.",
            # "The tenant has installed a makeshift observatory dome on the roof.",
            # "The tenant organizes weekly flea markets in the driveway.",
            # "The tenant has unauthorized large exercise equipment on the balcony.",
            # "The tenant uses part of the lawn for a large-scale model railway setup.",
            # "The tenant has constructed a zip line that crosses over the community pool.",
            # "The tenant holds frequent barbecue competitions in the common area.",
            # "The tenant has a collection of wind turbines on the roof, generating noise complaints.",
            # "The tenant uses the front yard for a permanent yard sale setup.",
            # "The tenant has set up a large fish farming pond in the backyard.",
            # "The tenant broadcasts live music sessions from their balcony.",
            # "The tenant has unauthorized large inflatable advertising characters during promotions.",
            # "The tenant uses the property’s exterior walls for mural painting workshops.",
            # "The tenant has installed a faux storefront on the ground floor.",
            # "The tenant organizes community potluck dinners without following proper channels.",
            # "The tenant has a makeshift batting cage that they use at all hours.",
            # "The tenant has unauthorized canopies over their parking spot.",
            # "The tenant keeps a collection of historical artillery pieces on display.",
            # "The tenant uses a large, noisy generator for backup power without permission.",
            # "The tenant has an outdoor art gallery that encroaches on communal spaces.",
            # "The tenant has installed a mini-golf course across their lawn and common grounds.",
            # "The tenant runs a weekend tutoring service that causes extra traffic.",
            # "The tenant has set up a seasonal pumpkin patch and corn maze on the property."
        ]

other_scenarios = [
    "The tenant lost their job.",
    "The tenant is undergoing a divorce.",
    "The tenant has been diagnosed with a serious illness.",
    "The tenant's child has moved back home, increasing expenses.",
    "The tenant is taking care of an elderly parent.",
    "The tenant has had a decrease in work hours.",
    "The tenant is dealing with identity theft issues.",
    "The tenant has been called for extended jury duty.",
    "The tenant is facing legal charges.",
    "The tenant is recovering from an accident.",
    "The tenant is dealing with flood damage in the apartment.",
    "The tenant's car was stolen, affecting their commute.",
    "The tenant is participating in extended volunteer work.",
    "The tenant is experiencing credit card fraud.",
    "The tenant is undergoing psychiatric treatment.",
    "The tenant has been affected by a scam.",
    "The tenant is dealing with a bedbug infestation.",
    "The tenant is experiencing harassment at work.",
    "The tenant is going through bankruptcy.",
    "The tenant has unexpected educational expenses.",
    "The tenant is facing unexpected travel costs due to a family emergency.",
    "The tenant is dealing with the death of a close family member.",
    "The tenant has had their bank account hacked.",
    "The tenant is experiencing severe allergies affecting their work.",
    "The tenant is adjusting to a new baby in the family.",
    "The tenant is involved in a custody battle.",
    "The tenant is dealing with vandalism to their personal property.",
    "The tenant has had a significant other move out, affecting their finances.",
    "The tenant is coping with a partner's unemployment.",
    "The tenant is attending night school and struggling with time management.",
    "The tenant is dealing with a problematic new roommate.",
    "The tenant is facing increased child care costs.",
    "The tenant has had a significant rent increase in another property they own.",
    "The tenant is dealing with the consequences of a natural disaster.",
    "The tenant is addressing issues from a previous rental scam.",
    "The tenant has recently undergone a major surgery.",
    "The tenant is dealing with the aftermath of a break-in.",
    "The tenant is coping with chronic pain.",
    "The tenant is struggling with mental health issues.",
    "The tenant is managing addiction recovery.",
    "The tenant is dealing with a rodent infestation in the apartment.",
    "The tenant's vehicle requires costly repairs.",
    "The tenant is updating their qualifications for their job.",
    "The tenant is starting a new business and facing initial financial strain.",
    "The tenant has been exposed to a toxic substance in the apartment.",
    "The tenant is engaged in a legal dispute over property.",
    "The tenant is undergoing debt restructuring.",
    "The tenant is dealing with loss of personal documents.",
    "The tenant is facing discrimination at work.",
    "The tenant has been displaced temporarily due to building repairs.",
    # "The tenant is dealing with mold removal in their unit.",
    # "The tenant is addressing issues from leaking appliances.",
    # "The tenant is fighting an incorrect billing issue with utilities.",
    # "The tenant is undergoing therapy for PTSD.",
    # "The tenant is managing side effects from a new medication.",
    # "The tenant is struggling with a long commute after a job change.",
    # "The tenant is dealing with increased living costs.",
    # "The tenant is experiencing internet fraud.",
    # "The tenant is resolving a dispute with a previous employer.",
    # "The tenant is dealing with a problematic landlord in another property.",
    # "The tenant is correcting a tax filing error.",
    # "The tenant is struggling to pay for necessary medical treatments.",
    # "The tenant is dealing with complications from a previous injury.",
    # "The tenant is navigating the legal system for the first time.",
    # "The tenant is disputing a wrongful bill.",
    # "The tenant is overcoming obstacles due to a lack of public services.",
    # "The tenant is facing eviction from another property they rent.",
    # "The tenant is challenging an unfair parking ticket.",
    # "The tenant is dealing with theft of their personal belongings.",
    # "The tenant is addressing issues with a difficult neighbor.",
    # "The tenant is coping with the impact of a stock market downturn on their investments.",
    # "The tenant is adjusting to life after incarceration.",
    # "The tenant is dealing with property damage from a recent storm.",
    # "The tenant is facing a sudden allergy to the apartment's new paint.",
    # "The tenant is managing recovery from a severe burn.",
    # "The tenant is coping with the consequences of identity fraud.",
    # "The tenant has been diagnosed with chronic fatigue syndrome.",
    # "The tenant's spouse has been laid off unexpectedly.",
    # "The tenant is undergoing cancer treatment.",
    # "The tenant is dealing with severe depression.",
    # "The tenant is facing unexpected veterinary expenses for a sick pet.",
    # "The tenant is attending therapy sessions for anxiety.",
    # "The tenant is dealing with the aftermath of a severe weather event.",
    # "The tenant has incurred unexpected expenses from a family illness.",
    # "The tenant is battling a lawsuit related to a past business.",
    # "The tenant's vehicle has been vandalized.",
    # "The tenant is dealing with the long-term effects of COVID-19.",
    # "The tenant is undergoing fertility treatments.",
    # "The tenant is managing the effects of a data breach on their personal information.",
    # "The tenant is trying to recover from financial losses due to a phishing scam.",
    # "The tenant is coping with the death of a partner.",
    # "The tenant is struggling with the sudden increase in utility bills.",
    # "The tenant is addressing water damage from a leaking roof.",
    # "The tenant is dealing with the repercussions of a false arrest.",
    # "The tenant is fighting a costly infestation of termites.",
    # "The tenant is facing significant repair costs for structural damage in their home.",
    # "The tenant is coping with grief from the loss of a close friend.",
    # "The tenant is adjusting to a sudden job relocation.",
    # "The tenant is dealing with a serious injury from a sports accident.",
    # "The tenant is managing symptoms of a rare disease.",
    # "The tenant is dealing with issues arising from a failed business venture.",
    # "The tenant is undergoing treatment for a newly diagnosed autoimmune disease.",
    # "The tenant is facing legal action from a breach of contract.",
    # "The tenant is experiencing difficulties due to an unreliable vehicle.",
    # "The tenant is dealing with a significant other suffering from addiction.",
    # "The tenant is managing issues related to aging parents.",
    # "The tenant is facing increased medical costs due to a chronic illness.",
    # "The tenant is dealing with a sudden infestation of ants.",
    # "The tenant is experiencing financial strain due to an unexpected inheritance issue.",
    # "The tenant is dealing with the fallout of a community dispute.",
    # "The tenant is navigating difficulties with a home renovation project.",
    # "The tenant is coping with the sudden death of a beloved pet.",
    # "The tenant is dealing with complications following an elective surgery.",
    # "The tenant is managing stress due to a high-stakes career change.",
    # "The tenant is facing harassment from a co-worker.",
    # "The tenant is dealing with a roof collapse at their residence.",
    # "The tenant is experiencing severe side effects from a medication change.",
    # "The tenant is struggling with financial obligations after adopting a child.",
    # "The tenant is dealing with a disruption due to nearby construction.",
    # "The tenant is facing challenges related to a severe learning disability.",
    # "The tenant is coping with the ramifications of a divorce settlement.",
    # "The tenant is struggling to manage the care of multiple foster children.",
    # "The tenant is dealing with severe anxiety from public speaking requirements at work.",
    # "The tenant is navigating the complexities of a multi-generational household.",
    # "The tenant is addressing a severe mold problem in their apartment.",
    # "The tenant is managing stress from a recent home burglary.",
    # "The tenant is undergoing financial difficulties due to a pyramid scheme.",
    # "The tenant is facing challenges due to an unexpected tax audit.",
    # "The tenant is coping with the sudden loss of a close relative.",
    # "The tenant is dealing with damage from a kitchen fire.",
    # "The tenant is experiencing difficulties after losing their driver's license.",
    # "The tenant is struggling with debt from multiple credit cards.",
    # "The tenant is undergoing treatment for Lyme disease.",
    # "The tenant is facing the challenge of learning a new language for work.",
    # "The tenant is coping with the effects of cyberbullying.",
    # "The tenant is dealing with a significant reduction in retirement funds.",
    # "The tenant is experiencing a severe case of the flu.",
    # "The tenant is managing the fallout from a public scandal.",
    # "The tenant is adjusting to a new life after moving from abroad.",
    # "The tenant is dealing with the aftermath of an earthquake.",
    # "The tenant is facing difficulties with a new adoption.",
    # "The tenant is managing the effects of seasonal affective disorder.",
    # "The tenant is coping with complications from diabetes.",
    # "The tenant is struggling with the upkeep of an older vehicle.",
    # "The tenant is dealing with a recent robbery at their workplace.",
    # "The tenant is facing eviction threats from another property they rent.",
    # "The tenant is dealing with the legal ramifications of a past conviction.",
    # "The tenant is navigating a dispute with a contractor over unfinished work.",
    # "The tenant is coping with the unexpected passing of their mentor.",
    # "The tenant is facing the challenges of adjusting to a prosthetic limb.",
    # "The tenant is dealing with rising costs of living without increased income.",
    # "The tenant is experiencing disruptions due to power outages.",
    # "The tenant is managing severe back pain from an office job.",
    # "The tenant is facing challenges from a newly diagnosed vision impairment.",
    # "The tenant is dealing with the emotional impact of a failed relationship.",
    # "The tenant is struggling with the demands of a high-profile legal case.",
    # "The tenant is facing issues due to a malfunctioning heating system.",
    # "The tenant is dealing with the complications of adopting a child internationally.",
    # "The tenant is struggling to cope with the demands of being a single parent.",
    # "The tenant is managing the stress of a competitive educational program.",
    # "The tenant is experiencing isolation due to working remotely.",
    # "The tenant is coping with the sudden responsibility of caring for a relative's children.",
    # "The tenant is dealing with severe weather impacts on their daily commute.",
    # "The tenant is facing a crisis due to a family member's drug addiction.",
    # "The tenant is adjusting to dietary changes due to health issues.",
    # "The tenant is managing the challenges of a new job with irregular hours.",
    # "The tenant is dealing with a defamation lawsuit.",
    # "The tenant is struggling to manage a chronic respiratory condition.",
    # "The tenant is facing difficulties due to the sudden death of a business partner.",
    # "The tenant is dealing with harassment from an ex-partner.",
    # "The tenant is coping with the financial strain of an unplanned pregnancy.",
    # "The tenant is managing a legal challenge regarding parental rights.",
    # "The tenant is dealing with the breakdown of essential home appliances.",
    # "The tenant is facing the stress of an upcoming competitive exam.", 
    # "The tenant is dealing with the fallout of a flood in their home.",
    # "The tenant is struggling with the costs of repairing a leaking plumbing system.",
    # "The tenant is facing legal issues related to a previous rental agreement.",
    # "The tenant is coping with the emotional distress of a recent miscarriage.",
    # "The tenant is managing the challenges of a new chronic illness diagnosis.",
    # "The tenant is dealing with the impact of a recent job demotion.",
    # "The tenant is adjusting to life without a primary caregiver.",
    # "The tenant is facing financial difficulties due to a failed investment.",
    # "The tenant is dealing with a severe rodent problem in their apartment.",
    # "The tenant is coping with the impact of a significant lifestyle change.",
    # "The tenant is managing the challenges of returning to school as an adult.",
    # "The tenant is dealing with the stress of a family member's criminal trial.",
    # "The tenant is adjusting to the complications of a dietary disorder.",
    # "The tenant is facing the repercussions of withdrawing from a professional exam.",
    # "The tenant is dealing with a major repair issue in their vehicle.",
    # "The tenant is coping with the stress of relocating to a new city.",
    # "The tenant is facing difficulties due to a pest infestation.",
    # "The tenant is adjusting to a new therapeutic regimen for mental health.",
    # "The tenant is managing the fallout from a social media mishap.",
    # "The tenant is coping with the effects of a significant weather-related disaster.",
    # "The tenant is dealing with unexpected complications from a routine surgery.",
    # "The tenant is struggling with the responsibilities of new pet ownership.",
    # "The tenant is adjusting to changes after a major religious conversion.",
    # "The tenant is facing challenges related to an aging vehicle.",
    # "The tenant is coping with the costs of a child's extracurricular activities.",
    # "The tenant is managing stress related to an unexpected job transfer.",
    # "The tenant is dealing with the complexities of a foreign visa process.",
    # "The tenant is coping with the emotional burden of elder care.",
    # "The tenant is managing the impact of a neighborhood crime wave.",
    # "The tenant is facing the challenges of a child's health diagnosis.",
    # "The tenant is dealing with a disruption caused by home renovation delays.",
    # "The tenant is managing anxiety related to public speaking engagements.",
    # "The tenant is dealing with the consequences of a personal financial audit.",
    # "The tenant is coping with the aftermath of a local community dispute.",
    # "The tenant is managing the challenges of a long-term disability.",
    # "The tenant is adjusting to the new demands of a freelance career.",
    # "The tenant is dealing with the aftermath of an international move.",
    # "The tenant is coping with the emotional effects of a major theft.",
    # "The tenant is managing the implications of a career-ending injury.",
    # "The tenant is dealing with the challenges of a major home appliance failure.",
    # "The tenant is facing the stress of a child moving out for college.",
    # "The tenant is managing the effects of a significant relationship conflict.",
    # "The tenant is coping with a sudden illness in the family.",
    # "The tenant is dealing with the financial burden of multiple loan repayments.",
    # "The tenant is managing the effects of a damaging hailstorm on their property.",
    # "The tenant is coping with the pressures of a high-stakes business deal.",
    # "The tenant is dealing with the effects of a significant other's career change.",
    # "The tenant is managing health issues related to poor air quality in their area.",
    # "The tenant is facing challenges related to a personal identity crisis.",
    # "The tenant is dealing with the stress of a significant legal victory.",
    # "The tenant is dealing with the emotional distress of witnessing a traumatic event.",
    # "The tenant is facing challenges due to a sudden increase in living expenses.",
    # "The tenant is managing complications from a long-term occupational injury.",
    # "The tenant is coping with the responsibilities of caring for a terminally ill family member.",
    # "The tenant is adjusting to the difficulties of balancing work and parenting.",
    # "The tenant is dealing with the aftermath of a significant financial fraud.",
    # "The tenant is facing legal issues from a disputed property boundary.",
    # "The tenant is coping with the loss of a major client at work.",
    # "The tenant is managing the stress of an upcoming major surgery.",
    # "The tenant is dealing with the challenges of sudden hearing loss.",
    # "The tenant is adjusting to a new life after a significant weight loss surgery.",
    # "The tenant is coping with the instability of temporary employment.",
    # "The tenant is dealing with the distress of a recent home invasion.",
    # "The tenant is facing challenges from a chronic skin condition.",
    # "The tenant is managing the difficulties of integrating into a new community.",
    # "The tenant is coping with the repercussions of a child's behavioral issues.",
    # "The tenant is dealing with the implications of a spouse's sudden job loss.",
    # "The tenant is facing the challenges of managing a chronic heart condition.",
    # "The tenant is coping with the strain of an intense academic program.",
    # "The tenant is managing the effects of a significant lifestyle restriction.",
    # "The tenant is dealing with the challenges of adopting a child with special needs.",
    # "The tenant is coping with the sudden requirement to care for a disabled sibling.",
    # "The tenant is managing the stress of a highly competitive sports season.",
    # "The tenant is facing difficulties due to an unstable housing market.",
    # "The tenant is coping with the demands of a high-profile job.",
    # "The tenant is dealing with the effects of a major technology failure at work.",
    # "The tenant is managing health issues arising from a toxic work environment.",
    # "The tenant is coping with the sudden loss of digital data critical to their business.",
    # "The tenant is facing challenges due to a significant other's mental health crisis.",
    # "The tenant is managing the repercussions of an unexpected legal summons.",
    # "The tenant is dealing with the fallout from a public relations crisis.",
    # "The tenant is coping with the consequences of a severe allergic reaction.",
    # "The tenant is facing challenges related to a problematic house renovation.",
    # "The tenant is managing the strain of a partner's chronic unemployment.",
    # "The tenant is dealing with the implications of a new, restrictive diet.",
    # "The tenant is coping with the emotional toll of a failing business.",
    # "The tenant is facing financial difficulties due to an increase in mortgage rates.",
    # "The tenant is managing the effects of a parental health crisis.",
    # "The tenant is coping with the aftermath of a neighborhood dispute.",
    # "The tenant is facing challenges from a severe storm damaging their property.",
    # "The tenant is dealing with the uncertainties of a major career shift.",
    # "The tenant is managing the stress of a divorce proceeding.",
    # "The tenant is coping with the difficulties of a significant career downturn.",
    # "The tenant is dealing with the challenges of learning a new skill late in life.",
    # "The tenant is managing health concerns related to environmental pollution.",
    # "The tenant is facing challenges due to a costly vehicle accident.",
    # "The tenant is coping with the complexities of managing a chronic illness in the family.",
    # "The tenant is dealing with the demands of a new educational certification.",
    # "The tenant is managing the strain of a new governmental regulation affecting their business.",
    # "The tenant is coping with the implications of a significant lifestyle change due to health advice."
]

def flip_bits(bits, k):
    flipped_bits = []
    for bit in bits:
        # Generate a random number and compare it with probability k
        if random.random() < k:
            # Flip the bit
            flipped_bit = 1 - bit
        else:
            flipped_bit = bit
        flipped_bits.append(flipped_bit)
    return flipped_bits



def generate_dataset(total_entries:int=500, percent_rtc_effective:float=0.3, percent_lease_violations:float=0.85, flip_rate:float=0.):
    rtc_effective_count = int(total_entries * percent_rtc_effective)
    leases_violations_count = int(rtc_effective_count * percent_lease_violations)
    other_issues_count = rtc_effective_count - leases_violations_count
    rtc_not_effective_count = total_entries - rtc_effective_count


    dataset = {'text': [], 
               'label': []}
    for _ in range(leases_violations_count):
        scenario = random.choice(leases_violations_scenarios)
        dataset['text'].append("The Right to Counsel is in effect in the tenant's zip code. " + scenario)
        dataset['label'].append(0)

    for _ in range(other_issues_count):
        scenario = random.choice(other_scenarios)
        dataset['text'].append("The Right to Counsel is in effect in the tenant's zip code. " + scenario)
        dataset['label'].append(1)
    
    for _ in range(rtc_not_effective_count):
        scenario = random.choice(other_scenarios + leases_violations_scenarios)
        dataset['text'].append("The Right to Counsel is not in effect in the tenant's zip code. " + scenario)
        dataset['label'].append(0)

    if flip_rate > 0:
        dataset['label'] = flip_bits(dataset['label'], flip_rate)

    return dataset
